package com.softwarepatterns.aiconsumptionplatform.service;

import com.softwarepatterns.aiconsumptionplatform.dto.GenerationRequest;
import com.softwarepatterns.aiconsumptionplatform.dto.GenerationResponse;
import org.springframework.stereotype.Service;

import java.time.LocalDateTime;

@Service
public class MockAIGenerationService implements AIGenerationService {

    private final TokenEstimator tokenEstimator;

    public MockAIGenerationService(TokenEstimator tokenEstimator) {
        this.tokenEstimator = tokenEstimator;
    }

    @Override
    public GenerationResponse generate(GenerationRequest request) {
        GenerationResponse response = new GenerationResponse();
        response.setGeneratedText(buildGeneratedText(request.getPrompt()));
        response.setTokensConsumed(tokenEstimator.estimateTokens(request.getPrompt()));
        response.setRequestAcceptedAt(LocalDateTime.now());
        return response;
    }

    private String buildGeneratedText(String prompt) {
        return "Mock AI response: " + prompt + " | This text was generated by the real subject service.";
    }
}
